apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-whale-blue
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-whale-app
  template:
    metadata:
      name: hello-blue-whale-pod
      labels:
        app: hello-whale-app
        version: blue
    spec:
      containers:
      - name: hello-whale-container
        image: vamsijakkula/hello-blue-whale:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
...
apiVersion: v1
kind: Service 
metadata:
  name: hello-whale-blue-svc
  labels:
    app: hello-whale-app
    version: blue
spec:
  selector:
    app: hello-whale-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
...
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: blue-ingress
spec:
 rules:
  - host: hello.whale
    http:
      paths:
      - backend:
          serviceName: hello-whale-blue-svc
          servicePort: 80
