apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-whale-green
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-whale-app
  template:
    metadata:
      name: hello-green-whale-pod
      labels:
        app: hello-whale-app
        version: green
    spec:
      containers:
      - name: hello-whale-container
        image: vamsijakkula/hello-green-whale:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
...
apiVersion: v1
kind: Service 
metadata:
  name: hello-whale-green-svc
  labels:
    app: hello-whale-app
    version: green
spec:
  selector:
    app: hello-whale-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
...
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
  name: green-ingress
spec:
 rules:
  - host: hello.whale
    http:
      paths:
      - backend:
          serviceName: hello-whale-green-svc
          servicePort: 80
