apiVersion: apps/v1
kind: Deployment
metadata:
  name: appv2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: appv2
  template:
    metadata:
      name: appv2-pod
      labels:
        app: appv2
        version: v2
    spec:
      containers:
      - name: appv2-container
        image: "appv2:latest"
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: appv2-svc
  labels:
    app: appv2
    version: v1
spec:
  selector:
    app: appv2
    ports:
        - port: 5000
          targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
  name: appv2-ingress
spec:
 rules:
  - host: canary.com
    http:
      paths:
            backend:
              service:
                name: appv2-svc
                port:
                  number: 30007
