apiVersion: apps/v1
kind: Deployment
metadata:
  name: appv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appv2
  template:
    metadata:
      name: appv2-pod
      labels:
        app: appv2
        version: v2
    spec:
      containers:
      - name: appv2-container
        image: "appv2:latest"
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: appv2-svc
  labels:
    app: appv2
    version: v2
spec:
  selector:
    app: appv2
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
  name: appv1-ingress
spec:
  rules:
    - host: ec2-3-109-157-218.ap-south-1.compute.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appv2-svc
                port:
                  number: 5000
