apiVersion: apps/v1
kind: Deployment
metadata:
  name: appv1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: appv1
  template:
    metadata:
      name: appv1-pod
      labels:
        app: appv1
        version: v1
    spec:
      containers:
      - name: appv1-container
        image: "appv1:latest"
        imagePullPolicy: Never
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: appv1-svc
  labels:
    app: appv1
    version: v1
spec:
  selector:
    app: appv1
  ports:
    - port: 6000
      targetPort: 6000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appv1-ingress
spec:
  rules:
    - host: canary.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appv1-svc
                port:
                  number: 6000
