apiVersion: apps/v1
kind: Deployment
metadata:
  name: appv2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: appv2
  template:
    metadata:
      name: appv1-pod
      labels:
        app: appv2
        version: v2
    spec:
      containers:
      - name: appv2-container
        image: "appv1:latest"
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v2
kind: Service
metadata:
  name: appv2-svc
  labels:
    app: appv2
    version: blue
spec:
  type: NodePort
  selector:
    app: hello-whale-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
  name: appv1-ingress
spec:
  rules:
    - host: canary.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appv2-svc
                port:
                  number: 30007
