name: CI
on:
  - push
jobs:
  job1:
    runs-on: self-hosted
    name: build app and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
        export SHELL=/bin/bash
        pwd
        ls
        eval $(minikube -p minikube docker-env)
        docker build -t appv1:latest ./appv1/
        docker build -t appv2:latest ./appv2/
        echo -n "verifying images:"
        docker images        
    - name: Deploy to minikube appv1 
      run:
        kubectl apply -f appv1menifest.yml
    - name: Deploy to minikube appv2
      run:
        kubectl apply -f appv2menifest.yaml
